/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'danos-add': RouteRecordInfo<'danos-add', '/danos/add', Record<never, never>, Record<never, never>>,
    'danos-list': RouteRecordInfo<'danos-list', '/danos/list', Record<never, never>, Record<never, never>>,
    'danos-list-id': RouteRecordInfo<'danos-list-id', '/danos/list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboard-dashboard': RouteRecordInfo<'dashboard-dashboard', '/dashboard/dashboard', Record<never, never>, Record<never, never>>,
    'dashboard-dashboard-client': RouteRecordInfo<'dashboard-dashboard-client', '/dashboard/dashboardClient', Record<never, never>, Record<never, never>>,
    'dashboard-dashboard-user': RouteRecordInfo<'dashboard-dashboard-user', '/dashboard/dashboardUser', Record<never, never>, Record<never, never>>,
    'front-pages-landing-page': RouteRecordInfo<'front-pages-landing-page', '/front-pages/landing-page', Record<never, never>, Record<never, never>>,
    'inmuebles-add-inmueble': RouteRecordInfo<'inmuebles-add-inmueble', '/inmuebles/addInmueble', Record<never, never>, Record<never, never>>,
    'inmuebles-history-inmueble': RouteRecordInfo<'inmuebles-history-inmueble', '/inmuebles/historyInmueble', Record<never, never>, Record<never, never>>,
    'inmuebles-list-alquiler': RouteRecordInfo<'inmuebles-list-alquiler', '/inmuebles/listAlquiler', Record<never, never>, Record<never, never>>,
    'inmuebles-list-ventas': RouteRecordInfo<'inmuebles-list-ventas', '/inmuebles/listVentas', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'novedades-add': RouteRecordInfo<'novedades-add', '/novedades/add', Record<never, never>, Record<never, never>>,
    'pagos-add-pago-form': RouteRecordInfo<'pagos-add-pago-form', '/pagos/add/pagoForm', Record<never, never>, Record<never, never>>,
    'pagos-list': RouteRecordInfo<'pagos-list', '/pagos/list', Record<never, never>, Record<never, never>>,
    'pagos-list-id': RouteRecordInfo<'pagos-list-id', '/pagos/list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'recibos-add': RouteRecordInfo<'recibos-add', '/recibos/add', Record<never, never>, Record<never, never>>,
    'recibos-list-id': RouteRecordInfo<'recibos-list-id', '/recibos/list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'recibos-list-list-recibos': RouteRecordInfo<'recibos-list-list-recibos', '/recibos/list/listRecibos', Record<never, never>, Record<never, never>>,
    'recibos-preview-id': RouteRecordInfo<'recibos-preview-id', '/recibos/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'roles-permisos': RouteRecordInfo<'roles-permisos', '/roles-permisos', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'servicios-publicos-add': RouteRecordInfo<'servicios-publicos-add', '/serviciosPublicos/add', Record<never, never>, Record<never, never>>,
    'servicios-publicos-list': RouteRecordInfo<'servicios-publicos-list', '/serviciosPublicos/list', Record<never, never>, Record<never, never>>,
    'servicios-publicos-list-id': RouteRecordInfo<'servicios-publicos-list-id', '/serviciosPublicos/list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
